import '../models/north_carolina_scratch_game.dart';

/// Snapshot of North Carolina Education Lottery's official Scratch-Off
/// remaining-prizes page. Refresh this catalog from that page as tickets are
/// launched or retired; it is not used as a source of heat-map locations.
class NorthCarolinaScratchCatalog {
  NorthCarolinaScratchCatalog._();

  static const officialSourceUrl =
      'https://nclottery.com/scratch-off-prizes-remaining';

  static final snapshotUpdatedAt = DateTime.parse('2026-08-25T00:00:00Z');

  static const games = <NorthCarolinaScratchGame>[
    NorthCarolinaScratchGame(
      id: '996',
      name: r'$1,000,000 Triple Play',
      topPrize: 1000000,
      topPrizesRemaining: 4,
    ),
    NorthCarolinaScratchGame(
      id: '995',
      name: r'$200,000 Triple Play',
      topPrize: 200000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '994',
      name: r'$25,000 Triple Play',
      topPrize: 25000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '993',
      name: r'$5,000 Triple Play',
      topPrize: 5000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '992',
      name: r'$2 MILLION VAULT',
      topPrize: 2000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '991',
      name: 'SPICY HOT RICHES',
      topPrize: 200000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '990',
      name: 'LADY LUCK',
      topPrize: 20000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '989',
      name: 'Maximum Money Blowout',
      topPrize: 2000,
      topPrizesRemaining: 289,
    ),
    NorthCarolinaScratchGame(
      id: '988',
      name: "Emerald 10's",
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '985',
      name: 'MAX-A-MILLION',
      topPrize: 1000000,
      topPrizesRemaining: 12,
    ),
    NorthCarolinaScratchGame(
      id: '984',
      name: 'Lucky Loteria®',
      topPrize: 1000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '981',
      name: '50X The Cash',
      topPrize: 1000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '980',
      name: '20X The Cash',
      topPrize: 250000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '976',
      name: '100X The Cash',
      topPrize: 2000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '975',
      name: r'$1,000,000 Money Rush',
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '972',
      name: r'$8 Million Money Maker',
      topPrize: 8000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '959',
      name: 'LOTERIA®',
      topPrize: 75000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '952',
      name: 'Millionaire Bucks',
      topPrize: 5000000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '951',
      name: 'Win Big',
      topPrize: 2000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '949',
      name: 'Xtreme Cashword',
      topPrize: 150000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '948',
      name: 'JUMBO BUCKS',
      topPrize: 1000000,
      topPrizesRemaining: 0,
    ),
    NorthCarolinaScratchGame(
      id: '947',
      name: 'MEGA BUCKS',
      topPrize: 200000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '946',
      name: 'Junior BIG OL\' BUCKS®',
      topPrize: 50000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '944',
      name: r'$50,000 Payout',
      topPrize: 50000,
      topPrizesRemaining: 42,
    ),
    NorthCarolinaScratchGame(
      id: '940',
      name: 'Supreme 7s',
      topPrize: 4000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '939',
      name: r'$80 Million Cash Blowout',
      topPrize: 500,
      topPrizesRemaining: 1291,
    ),
    NorthCarolinaScratchGame(
      id: '932',
      name: 'Instant Millions',
      topPrize: 2000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '928',
      name: r'$400,000 Jackpot',
      topPrize: 400000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '925',
      name: '200X The Cash',
      topPrize: 5000000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '917',
      name: r'$2,000,000 Diamond Deluxe',
      topPrize: 2000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '892',
      name: 'Black Titanium',
      topPrize: 4000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '876',
      name: r'$5,000,000 Ultimate',
      topPrize: 5000000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '868',
      name: '100X The Cash',
      topPrize: 2000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '54',
      name: 'Massive Cash Blowout',
      topPrize: 3000,
      topPrizesRemaining: 3247,
    ),
    NorthCarolinaScratchGame(
      id: '53',
      name: 'CASH',
      topPrize: 200000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '52',
      name: 'Loteria Grande',
      topPrize: 150000,
      topPrizesRemaining: 5,
    ),
    NorthCarolinaScratchGame(
      id: '51',
      name: r'Hit $50!',
      topPrize: 5000,
      topPrizesRemaining: 4,
    ),
    NorthCarolinaScratchGame(
      id: '50',
      name: 'Jackpot Millions',
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '49',
      name: 'Triple Red 777 Jackpot',
      topPrize: 1000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '48',
      name: 'Wheel of Fortune',
      topPrize: 200000,
      topPrizesRemaining: 4,
    ),
    NorthCarolinaScratchGame(
      id: '47',
      name: 'Corner Payout',
      topPrize: 20000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '46',
      name: 'Jumbo Bucks',
      topPrize: 1000000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '45',
      name: 'Mega Bucks',
      topPrize: 200000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '44',
      name: 'Jr Big Ol Bucks',
      topPrize: 50000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '43',
      name: 'Extreme Money Blowout',
      topPrize: 2000,
      topPrizesRemaining: 3721,
    ),
    NorthCarolinaScratchGame(
      id: '42',
      name: 'Jungle Cashword',
      topPrize: 150000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '41',
      name: 'Diamonds and Dollars',
      topPrize: 200000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '40',
      name: 'Lucky 7s',
      topPrize: 7000,
      topPrizesRemaining: 7,
    ),
    NorthCarolinaScratchGame(
      id: '39',
      name: '20 Years',
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '38',
      name: 'Big Cash Blowout',
      topPrize: 500,
      topPrizesRemaining: 4021,
    ),
    NorthCarolinaScratchGame(
      id: '37',
      name: 'Prize Link Connect',
      topPrize: 200000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '36',
      name: r'Easy $100s',
      topPrize: 20000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '35',
      name: r'$100,000 Cash Payday',
      topPrize: 100000,
      topPrizesRemaining: 56,
    ),
    NorthCarolinaScratchGame(
      id: '34',
      name: 'LOTERIA™ MULTIPLIER',
      topPrize: 1000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '33',
      name: r'$500 Frenzy',
      topPrize: 500,
      topPrizesRemaining: 7242,
    ),
    NorthCarolinaScratchGame(
      id: '32',
      name: '500X The Cash',
      topPrize: 10000000,
      topPrizesRemaining: 5,
    ),
    NorthCarolinaScratchGame(
      id: '31',
      name: '50X The Cash',
      topPrize: 1000000,
      topPrizesRemaining: 10,
    ),
    NorthCarolinaScratchGame(
      id: '30',
      name: '20X The Cash',
      topPrize: 250000,
      topPrizesRemaining: 12,
    ),
    NorthCarolinaScratchGame(
      id: '29',
      name: '10X The Cash',
      topPrize: 50000,
      topPrizesRemaining: 9,
    ),
    NorthCarolinaScratchGame(
      id: '28',
      name: '5X The Cash',
      topPrize: 10000,
      topPrizesRemaining: 9,
    ),
    NorthCarolinaScratchGame(
      id: '27',
      name: 'Stacks of Cash',
      topPrize: 2000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '26',
      name: 'Cash King',
      topPrize: 200000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '25',
      name: '777',
      topPrize: 20000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '24',
      name: '200X The Cash',
      topPrize: 5000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '23',
      name: r'$10 MONOPOLY®',
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '22',
      name: r'$5 MONOPOLY®',
      topPrize: 200000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '21',
      name: 'Winter Winfall',
      topPrize: 250000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '19',
      name: 'Holiday Cashword',
      topPrize: 150000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '18',
      name: 'Peppermint Payout',
      topPrize: 150000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '17',
      name: 'White Elephant',
      topPrize: 20000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '16',
      name: r'Holiday $100s',
      topPrize: 5000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '15',
      name: 'Ultimate Blowout',
      topPrize: 5000,
      topPrizesRemaining: 55,
    ),
    NorthCarolinaScratchGame(
      id: '14',
      name: 'Magnificent Millions',
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '13',
      name: 'High Voltage Cash',
      topPrize: 200000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '12',
      name: 'Cash Drop',
      topPrize: 20000,
      topPrizesRemaining: 3,
    ),
    NorthCarolinaScratchGame(
      id: '11',
      name: r'$1,000,000 Bonus Match',
      topPrize: 1000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '10',
      name: 'Double Your Money',
      topPrize: 200000,
      topPrizesRemaining: 0,
    ),
    NorthCarolinaScratchGame(
      id: '8',
      name: "Ruby Red 7's",
      topPrize: 2000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '7',
      name: 'Cashword King',
      topPrize: 1000000,
      topPrizesRemaining: 1,
    ),
    NorthCarolinaScratchGame(
      id: '6',
      name: 'Jurassic Park',
      topPrize: 200000,
      topPrizesRemaining: 0,
    ),
    NorthCarolinaScratchGame(
      id: '5',
      name: r'$50 Frenzy',
      topPrize: 5000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '4',
      name: 'Carolina Black Premier',
      topPrize: 4000000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '3',
      name: r'Hot $2,000',
      topPrize: 2000,
      topPrizesRemaining: 459,
    ),
    NorthCarolinaScratchGame(
      id: '2',
      name: 'LOTERIA® Fiesta',
      topPrize: 150000,
      topPrizesRemaining: 2,
    ),
    NorthCarolinaScratchGame(
      id: '1',
      name: '5 Times Lucky',
      topPrize: 200000,
      topPrizesRemaining: 1,
    ),
  ];
}
