import '../models/state_scratch_game.dart';
import 'package:flutter/foundation.dart';

/// Verified, ticket-level Scratch-Off snapshots shared by every state.
///
/// A state is added here only when its official catalog supplies a ticket
/// name, game number, price, and top prize. A snapshot can cover a specific
/// official collection (such as newly launched tickets) rather than every
/// active ticket. Retailer-location records remain separate in the activity
/// feed because a catalog alone cannot paint a heat map honestly.
class StateScratchCatalogRegistry {
  StateScratchCatalogRegistry._();

  /// These compact, ticket-level snapshots are taken from each lottery's
  /// official active-game page. They intentionally stay separate from the
  /// activity feed: an active ticket is not evidence of a winning ticket at a
  /// particular retailer.
  static const Map<String, List<StateScratchGame>> _catalogs = {
    'California': [
      StateScratchGame(
        stateName: 'California',
        id: '1740',
        name: '200X',
        cost: 30,
        topPrize: 10000000,
      ),
      StateScratchGame(
        stateName: 'California',
        id: '1738',
        name: r'$50 or $100',
        cost: 10,
        topPrize: 100,
      ),
      StateScratchGame(
        stateName: 'California',
        id: '1736',
        name: 'Set for Life',
        cost: 2,
        topPrize: 1200000,
        topPrizeLabel: r'$4,000 a month for 25 years',
      ),
      StateScratchGame(
        stateName: 'California',
        id: '1737',
        name: 'LOTERIA™ Extra!',
        cost: 5,
        topPrize: 100000,
      ),
      StateScratchGame(
        stateName: 'California',
        id: '1739',
        name: 'Instant Prize Crossword',
        cost: 20,
        topPrize: 2000000,
      ),
    ],
    'Georgia': [
      StateScratchGame(
        stateName: 'Georgia',
        id: '1890',
        name: r'$500,000 Ca$h Blowout',
        cost: 20,
        topPrize: 500000,
      ),
      StateScratchGame(
        stateName: 'Georgia',
        id: '1876',
        name: r'$1,500,000 MAX',
        cost: 10,
        topPrize: 1500000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Georgia',
        id: '1855',
        name: r'$1,000,000 Triple Match',
        cost: 10,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Georgia',
        id: '1715',
        name: r'$2 Million Multiplier',
        cost: 20,
        topPrize: 2000000,
        topPrizesRemaining: 1,
      ),
    ],
    'Pennsylvania': [
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1801',
        name: 'THE WIZARD OF OZ™ GLINDA THE GOOD WITCH',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 10,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1800',
        name: 'Winner Winner Chicken Dinner',
        cost: 2,
        topPrize: 25000,
        topPrizesRemaining: 10,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1799',
        name: 'THE WIZARD OF OZ™ YELLOW BRICK ROAD',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 10,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1798',
        name: 'THE WIZARD OF OZ™ THE GREAT AND POWERFUL OZ',
        cost: 10,
        topPrize: 400000,
        topPrizesRemaining: 8,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1797',
        name: 'Snake, Rattle and Roll',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1796',
        name: r'Ca$h Money',
        cost: 50,
        topPrize: 4000000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1795',
        name: r'Bright Buck$',
        cost: 1,
        topPrize: 2500,
        topPrizesRemaining: 12,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1794',
        name: r'$20 Frenzy',
        cost: 2,
        topPrize: 2000,
        topPrizesRemaining: 76,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1793',
        name: 'Crossword Deluxe',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 7,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1792',
        name: 'Wild Side',
        cost: 5,
        topPrize: 150000,
        topPrizesRemaining: 9,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1791',
        name: 'VIP Bonus Cash',
        cost: 10,
        topPrize: 750000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1790',
        name: r'$1,500,000 Super Star',
        cost: 30,
        topPrize: 1500000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1789',
        name: 'Super 7s',
        cost: 2,
        topPrize: 17000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1788',
        name: 'Lights, Camera, Crossword',
        cost: 3,
        topPrize: 30000,
        topPrizesRemaining: 8,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1787',
        name: 'Fever Doubler',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1786',
        name: 'Ruby Rich3s',
        cost: 10,
        topPrize: 300000,
        topPrizesRemaining: 9,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1785',
        name: 'THE GAME OF LIFE',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1784',
        name: 'Million Dollar Win It All',
        cost: 50,
        topPrize: 1000000,
        topPrizesRemaining: 17,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1783',
        name: 'GOLD FISH®',
        cost: 1,
        topPrize: 2500,
        topPrizesRemaining: 11,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1782',
        name: 'GUS®',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 8,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1781',
        name: 'Win Win Win',
        cost: 10,
        topPrize: 1000000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1780',
        name: 'Triple Red 777',
        cost: 30,
        topPrize: 1000000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1779',
        name: 'A Latte Money',
        cost: 1,
        topPrize: 10000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1778',
        name: 'Money Rush',
        cost: 2,
        topPrize: 5000,
        topPrizesRemaining: 15,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1777',
        name: 'Money Box Bingo',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1776',
        name: r'$100 Blowout',
        cost: 5,
        topPrize: 100,
        topPrizesRemaining: 15360,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1775',
        name: r'$250 Blowout',
        cost: 10,
        topPrize: 250,
        topPrizesRemaining: 38901,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1774',
        name: r'$500 Blowout',
        cost: 20,
        topPrize: 500,
        topPrizesRemaining: 31647,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1773',
        name: '5 Star Wins',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1772',
        name: 'Find the Leprechaun',
        cost: 2,
        topPrize: 10000,
        topPrizesRemaining: 7,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1771',
        name: 'Big Bonus Triple Play',
        cost: 5,
        topPrize: 130000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1770',
        name: 'PHILADELPHIA 76ERS',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1769',
        name: 'Code Word Crossword',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1768',
        name: r'$120,000,000 Payout',
        cost: 30,
        topPrize: 2500000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1767',
        name: r'$500 a Week for Life',
        cost: 1,
        topPrize: 350000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1766',
        name: 'LOVE IS BLIND',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1765',
        name: r'$10,000 a Month for Life',
        cost: 5,
        topPrize: 1600000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1764',
        name: r'$20,000 a Month for Life',
        cost: 10,
        topPrize: 3200000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1763',
        name: r'$500,000 a Year for Life',
        cost: 20,
        topPrize: 7250000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1762',
        name: r'$1,000,000 a Year for Life',
        cost: 50,
        topPrize: 14500000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1761',
        name: 'Ho Ho Ho',
        cost: 1,
        topPrize: 500,
        topPrizesRemaining: 66,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1760',
        name: 'Snow Place Like Home',
        cost: 2,
        topPrize: 10000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1759',
        name: 'Trim the Tree X-word',
        cost: 3,
        topPrize: 30000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1758',
        name: 'ELF',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1757',
        name: r'$2,500 Festive Frenzy',
        cost: 10,
        topPrize: 2500,
        topPrizesRemaining: 175,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1756',
        name: r'Fro$ted Fortune',
        cost: 20,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1755',
        name: 'Merry Money Match',
        cost: 30,
        topPrize: 1000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1754',
        name: r'Mini Monsters $100 Blowout',
        cost: 2,
        topPrize: 100,
        topPrizesRemaining: 7249,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1753',
        name: 'Crossword Extra',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1752',
        name: 'Winning 7s',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1751',
        name: 'Extreme Green',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1750',
        name: 'Cash Spectacular',
        cost: 30,
        topPrize: 1500000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1749',
        name: 'Simply A Buck',
        cost: 1,
        topPrize: 1000,
        topPrizesRemaining: 9,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1748',
        name: 'Money Maker',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1747',
        name: 'JURASSIC PARK',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1746',
        name: 'Millionaire Loading',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1745',
        name: 'Win Pigs Fly',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1744',
        name: 'Goat Load of Cash Crossword',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1743',
        name: r'$50, $100 or $500',
        cost: 10,
        topPrize: 500,
        topPrizesRemaining: 449,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1742',
        name: r'$3 Million Mega Moolah Multiplier',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1741',
        name: 'Win It All',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1740',
        name: 'Bonus Ball Bingo',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1739',
        name: 'MONOPOLY SECRET VAULT',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1738',
        name: 'Jackpot',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1737',
        name: 'Neon 9s',
        cost: 2,
        topPrize: 9000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1736',
        name: 'High 5',
        cost: 5,
        topPrize: 155000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1735',
        name: 'Six Figures',
        cost: 10,
        topPrize: 600000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1734',
        name: '3s a Charm',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1733',
        name: '20X the Cash',
        cost: 1,
        topPrize: 2000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1732',
        name: '50X the Cash',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1731',
        name: 'Blingo',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1730',
        name: '100X the Cash',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1729',
        name: '200X the Cash',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1728',
        name: 'Sham-rockin’ Surprize',
        cost: 1,
        topPrize: 1700,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1727',
        name: 'Four Leaf Frenzy',
        cost: 2,
        topPrize: 17000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1726',
        name: 'Lucky Luck',
        cost: 5,
        topPrize: 70000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1725',
        name: 'All About Money',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1724',
        name: 'Lady Luck',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1723',
        name: r'The Hunt for $3,000,000',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1721',
        name: 'BETTY BOOP™',
        cost: 2,
        topPrize: 14000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1719',
        name: r'Fast $1,000',
        cost: 10,
        topPrize: 100000,
        topPrizesRemaining: 19,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1718',
        name: r'$1,000,000 Winnings',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1717',
        name: r'$5,000,000 Lion’s Share',
        cost: 50,
        topPrize: 5000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1716',
        name: 'Nutcracker Cash',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1714',
        name: 'Candy Cane Count-Up',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1713',
        name: 'NATIONAL LAMPOON’S CHRISTMAS VACATION',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1711',
        name: 'Jingle Jangle Jackpot',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1709',
        name: 'Pick Your Potion',
        cost: 2,
        topPrize: 13000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1708',
        name: 'Witches Brew Bucks',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1707',
        name: 'Lucky 13',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1706',
        name: 'GAME OF THRONES™',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1705',
        name: r'$3,000,000 Golden Ticket',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1704',
        name: 'UNO',
        cost: 1,
        topPrize: 10000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1703',
        name: 'S’more Crossword',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1702',
        name: r'Power $500',
        cost: 5,
        topPrize: 50000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1701',
        name: r'$500,000 Bonus Crossword',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1700',
        name: 'All Cash',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1698',
        name: 'Giant Bucks',
        cost: 5,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1697',
        name: 'Jumbo Bucks',
        cost: 10,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1696',
        name: 'Mega Bucks',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1695',
        name: 'Cash To Go',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1694',
        name: r'Ca$h Overload Crossword',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1693',
        name: 'Keys and Cash',
        cost: 5,
        topPrize: 5000,
        topPrizeLabel: 'Vehicle',
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1692',
        name: 'Big Cash Payout',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1690',
        name: 'Crossword Bonus Cash',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1687',
        name: r'Instant $1,000,000 Jackpot',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1684',
        name: 'CLUE',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1683',
        name: 'Red Hot 5s',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1682',
        name: r'$160 Million Cash Blowout',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1674',
        name: r'$100 or $1,000',
        cost: 30,
        topPrize: 1000,
        topPrizesRemaining: 22976,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1671',
        name: 'Bonus Star Bingo',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1669',
        name: r'$1 Million Moneybag Crossword',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1668',
        name: 'MONOPOLY Own It All',
        cost: 50,
        topPrize: 5000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1652',
        name: 'Double Your Dollars',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1627',
        name: '20X the Money',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1610',
        name: 'Sleigh Ride',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1605',
        name: r'Ghost$ and Goblin$',
        cost: 1,
        topPrize: 2500,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1596',
        name: 'It’s Your Lucky Day',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1592',
        name: 'Gus®',
        cost: 5,
        topPrize: 200000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1584',
        name: 'Multiplier Mania',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1582',
        name: 'The Best Dad Ever',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1579',
        name: r'$20,000 Lucky Win',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1578',
        name: 'Cash Craze Double Doubler',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1577',
        name: 'The Best Mom Ever',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1573',
        name: '333',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1572',
        name: r'$50,000 Count Up',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1571',
        name: 'Hello 50',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1569',
        name: 'Shamrock Green',
        cost: 1,
        topPrize: 2500,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1568',
        name: 'Leprechaun Loot',
        cost: 2,
        topPrize: 10000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1567',
        name: 'Four Leaf Fortune',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1566',
        name: 'Cash',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1565',
        name: 'THE WIZARD OF OZ™',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1564',
        name: 'Perfect Match',
        cost: 1,
        topPrize: 2500,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1563',
        name: 'My Lucky Valentine',
        cost: 2,
        topPrize: 14000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1561',
        name: 'Love 2 Win',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1560',
        name: r'$1,000,000 Power Payday',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1559',
        name: r'$5 Million Money Maker',
        cost: 50,
        topPrize: 5000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1558',
        name: r'Fast Ca$h',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1557',
        name: 'All About the Benjamins',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1556',
        name: r'$500,000 Crossword Mania',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1554',
        name: 'Gnome for the Holidays',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1553',
        name: 'Gingerbread Dough',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1552',
        name: 'Naughty or Nice',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1551',
        name: r'Ho Ho Whole Lotta $500s',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1550',
        name: 'Snow Much Fun',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1549',
        name: r'$1,000,000 Merry and Bright',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1547',
        name: 'MONOPOLY 20X',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1546',
        name: 'MONOPOLY 50X',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1545',
        name: 'MONOPOLY 100X',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1544',
        name: r'Boo Buck$',
        cost: 1,
        topPrize: 2500,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1543',
        name: 'Monster Money',
        cost: 2,
        topPrize: 13000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1540',
        name: 'WILLY WONKA GOLDEN TICKET™',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1539',
        name: r'Ca$h Incline',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1536',
        name: 'Solid Gold',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1535',
        name: r'$1,000,000 Extreme Green',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1534',
        name: 'Hot Ticket',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1533',
        name: r'Bonus Buck$',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1532',
        name: 'On the Money',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1531',
        name: r'Show Me $500,000',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1530',
        name: r'$3,000,000 Payout',
        cost: 30,
        topPrize: 3000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1529',
        name: 'Bee Lucky',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1528',
        name: 'Scoop Up Some Cash',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 6,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1527',
        name: 'Triple 333',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1526',
        name: 'Digging for Treasure',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1525',
        name: 'Feelin’ Like a Million Bucks',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1524',
        name: 'Wild Win',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1523',
        name: '7-11-21® LIVE!',
        cost: 2,
        topPrize: 21000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1522',
        name: 'The Hunt for Cash',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1521',
        name: 'Bigger Money Bingo',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1519',
        name: r'2 for $1',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1518',
        name: 'Cash Craze',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1517',
        name: 'Bolt Bucks',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1516',
        name: 'The Money Game',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1515',
        name: 'Mining for Millions',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1514',
        name: 'MONOPOLY 10X®',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1507',
        name: 'Color Block Crossword',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1498',
        name: r'Wild Ca$h Multiplier',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1493',
        name: r'$500 Cash Money',
        cost: 5,
        topPrize: 250000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1492',
        name: r'$500,000 Mega Crossword',
        cost: 10,
        topPrize: 500000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1430',
        name: r'Snowball Buck$',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1419',
        name: 'Rocket Crossword',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1410',
        name: '9s in a Line',
        cost: 2,
        topPrize: 9000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1372',
        name: 'Reindeer Games',
        cost: 1,
        topPrize: 5000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1371',
        name: 'Frosty the Doughman',
        cost: 2,
        topPrize: 20000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1370',
        name: r'Sleigh Bell$',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1369',
        name: 'Cash Kringle',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1367',
        name: 'Merry Millionaire',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1363',
        name: "Jack O' Lantern Jackpot",
        cost: 5,
        topPrize: 50000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1336',
        name: 'My First Million',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1334',
        name: r'$2 MONOPOLY™',
        cost: 2,
        topPrize: 25000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1331',
        name: r'$10 MONOPOLY™',
        cost: 10,
        topPrize: 300000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1328',
        name: 'Extreme 8s',
        cost: 3,
        topPrize: 50000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1326',
        name: 'Bingo Squared',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1323',
        name: '10X the Bucks',
        cost: 2,
        topPrize: 10000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1317',
        name: 'Bingo',
        cost: 3,
        topPrize: 60000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1314',
        name: 'Big Money Millionaire',
        cost: 20,
        topPrize: 1000000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1313',
        name: 'Lucky Numbers',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1301',
        name: 'Winning Vault',
        cost: 5,
        topPrize: 100000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1280',
        name: 'Quick Cash',
        cost: 1,
        topPrize: 10000,
        topPrizesRemaining: 0,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1270',
        name: r'$$$',
        cost: 1,
        topPrize: 10000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1264',
        name: '9s In A Line',
        cost: 1,
        topPrize: 9000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'Pennsylvania',
        id: '1258',
        name: 'Road to Riches',
        cost: 1,
        topPrize: 10000,
        topPrizesRemaining: 1,
      ),
    ],
    'Florida': [
      StateScratchGame(
        stateName: 'Florida',
        id: '1641',
        name: 'POWER 20X',
        cost: 5,
        topPrize: 1000000,
      ),
      StateScratchGame(
        stateName: 'Florida',
        id: '5063',
        name: r'CA$H IN HAND',
        cost: 10,
        topPrize: 2000000,
      ),
      StateScratchGame(
        stateName: 'Florida',
        id: '1642',
        name: r'$500,000 Cash Blitz',
        cost: 50,
        topPrize: 500000,
      ),
    ],
    'Tennessee': [
      StateScratchGame(
        stateName: 'Tennessee',
        id: '1387',
        name: r'All The Money $$$',
        cost: 20,
        topPrize: 1000000,
      ),
      StateScratchGame(
        stateName: 'Tennessee',
        id: '1386',
        name: '24K Gold',
        cost: 10,
        topPrize: 300000,
      ),
      StateScratchGame(
        stateName: 'Tennessee',
        id: '1384',
        name: 'Times 10 Bonus',
        cost: 2,
        topPrize: 20000,
      ),
      StateScratchGame(
        stateName: 'Tennessee',
        id: '1383',
        name: 'Lucky Gems',
        cost: 1,
        topPrize: 5000,
      ),
    ],
    'Virginia': [
      StateScratchGame(
        stateName: 'Virginia',
        id: '2310',
        name: '20X The Money',
        cost: 10,
        topPrize: 1000000,
      ),
      StateScratchGame(
        stateName: 'Virginia',
        id: '2391',
        name: 'Shamrock 7s',
        cost: 2,
        topPrize: 20000,
      ),
      StateScratchGame(
        stateName: 'Virginia',
        id: '2352',
        name: 'Double Sided Dollars',
        cost: 5,
        topPrize: 100000,
      ),
      StateScratchGame(
        stateName: 'Virginia',
        id: '2316',
        name: '2X The Money',
        cost: 1,
        topPrize: 4000,
      ),
    ],
    'Kentucky': [
      StateScratchGame(
        stateName: 'Kentucky',
        id: '150',
        name: r'$30 Set For Life',
        cost: 30,
        topPrize: 3120000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '152',
        name: r'$10 Set For Life',
        cost: 10,
        topPrize: 1040000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '153',
        name: r'$5 Set For Life',
        cost: 5,
        topPrize: 520000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '139',
        name: r'$750,000 Extravaganza',
        cost: 20,
        topPrize: 750000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '142',
        name: '24K Gold',
        cost: 20,
        topPrize: 500000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '128',
        name: 'Deluxe Gold',
        cost: 30,
        topPrize: 1500000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '131',
        name: 'Diamonds',
        cost: 5,
        topPrize: 100000,
      ),
      StateScratchGame(
        stateName: 'Kentucky',
        id: '112',
        name: 'Monopoly 50X',
        cost: 5,
        topPrize: 100000,
      ),
    ],
    'Maryland': [
      StateScratchGame(
        stateName: 'Maryland',
        id: '803',
        name: 'Triple Red 777s',
        cost: 20,
        topPrize: 1000000,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '802',
        name: 'Triple Red 7s Multiplier',
        cost: 10,
        topPrize: 77777,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '801',
        name: 'Triple Red 7s Tripler',
        cost: 5,
        topPrize: 57777,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '800',
        name: 'Triple Red 7s Doubler',
        cost: 2,
        topPrize: 7777,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '795',
        name: 'Diamonds & Gold',
        cost: 30,
        topPrize: 2000000,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '787',
        name: 'Money',
        cost: 10,
        topPrize: 250000,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '786',
        name: 'Winning Streak',
        cost: 5,
        topPrize: 50000,
      ),
      StateScratchGame(
        stateName: 'Maryland',
        id: '776',
        name: r'$5,000,000 LUXE',
        cost: 50,
        topPrize: 5000000,
      ),
    ],
    'Delaware': [
      StateScratchGame(
        stateName: 'Delaware',
        id: '512',
        name: 'MONOPOLY 5X',
        cost: 1,
        topPrize: 1000,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '513',
        name: 'MONOPOLY 10X',
        cost: 2,
        topPrize: 5000,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '514',
        name: 'MONOPOLY 20X',
        cost: 5,
        topPrize: 20000,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '510',
        name: 'LOTERIA FIESTA',
        cost: 5,
        topPrize: 10000,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '531',
        name: 'Deluxe Bucks',
        cost: 5,
        topPrize: 12000,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '518',
        name: 'CROSSWORD X-TRA 7S',
        cost: 5,
        topPrize: 10000,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '517',
        name: '777',
        cost: 2,
        topPrize: 2500,
      ),
      StateScratchGame(
        stateName: 'Delaware',
        id: '499',
        name: 'Power 7',
        cost: 2,
        topPrize: 2500,
      ),
    ],
    'New Jersey': [
      StateScratchGame(
        stateName: 'New Jersey',
        id: '01961',
        name: 'Cash Lines',
        cost: 1,
        topPrize: 500,
      ),
      StateScratchGame(
        stateName: 'New Jersey',
        id: '01968',
        name: 'Crossword Xtreme',
        cost: 30,
        topPrize: 600000,
      ),
      StateScratchGame(
        stateName: 'New Jersey',
        id: '2026-10x',
        name: '10X',
        cost: 2,
        topPrize: 20000,
      ),
      StateScratchGame(
        stateName: 'New Jersey',
        id: '2026-20x',
        name: r'$20X',
        cost: 5,
        topPrize: 200000,
      ),
      StateScratchGame(
        stateName: 'New Jersey',
        id: '2026-50x',
        name: r'$50X',
        cost: 10,
        topPrize: 500000,
      ),
      StateScratchGame(
        stateName: 'New Jersey',
        id: '2026-100x',
        name: r'$100X',
        cost: 20,
        topPrize: 1000000,
      ),
      StateScratchGame(
        stateName: 'New Jersey',
        id: '2026-jersey-riches',
        name: 'Jersey Riches',
        cost: 30,
        topPrize: 3000000,
      ),
    ],
    'New York': [
      StateScratchGame(
        stateName: 'New York',
        id: '1700',
        name: 'MILLIONAIRE RICHES',
        cost: 20,
        topPrize: 5000000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1701',
        name: 'HOT DOG!',
        cost: 5,
        topPrize: 500000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1702',
        name: 'DIAMOND CASHWORD',
        cost: 3,
        topPrize: 60000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1697',
        name: r'$3,000,000 MAX MULTIPLIER',
        cost: 10,
        topPrize: 3000000,
        topPrizesRemaining: 3,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1699',
        name: 'LUCKY 7s',
        cost: 1,
        topPrize: 7000,
        topPrizesRemaining: 18,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1698',
        name: 'DOUBLE YOUR MONEY',
        cost: 5,
        topPrize: 500000,
        topPrizesRemaining: 1,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1694',
        name: r'$2,000,000 100X CASHWORD',
        cost: 20,
        topPrize: 2000000,
        topPrizesRemaining: 4,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1696',
        name: 'MATCH 7s',
        cost: 3,
        topPrize: 70000,
        topPrizesRemaining: 5,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1695',
        name: 'POT OF GOLD',
        cost: 5,
        topPrize: 500000,
        topPrizesRemaining: 2,
      ),
      StateScratchGame(
        stateName: 'New York',
        id: '1691',
        name: '300X THE MONEY',
        cost: 30,
        topPrize: 10000000,
        topPrizesRemaining: 3,
      ),
    ],
    'Ohio': [
      StateScratchGame(
        stateName: 'Ohio',
        id: '1088',
        name: 'Sapphire Blue',
        cost: 1,
        topPrize: 777,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1089',
        name: 'Bonus Cash Wheel',
        cost: 5,
        topPrize: 150000,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1090',
        name: 'Instant Jackpot',
        cost: 10,
        topPrize: 500000,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1091',
        name: 'Millionaire Blowout',
        cost: 50,
        topPrize: 1000000,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1076',
        name: 'Electric 8s',
        cost: 1,
        topPrize: 500,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1077',
        name: 'Aces and 8s',
        cost: 5,
        topPrize: 150000,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1078',
        name: 'Cross Match Bingo',
        cost: 10,
        topPrize: 500000,
      ),
      StateScratchGame(
        stateName: 'Ohio',
        id: '1079',
        name: 'Wild Cash Tripler',
        cost: 30,
        topPrize: 3000000,
      ),
    ],
    'West Virginia': [
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1262',
        name: 'Bringing Six Back',
        cost: 10,
        topPrize: 60000,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1263',
        name: "I Can't Even 5",
        cost: 5,
        topPrize: 5000,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1261',
        name: 'Wild Red 7s',
        cost: 20,
        topPrize: 70000,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1274',
        name: 'The Cash Game - Go Big Money',
        cost: 10,
        topPrize: 50000,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1267',
        name: 'Pickle Graffiti Bow Wow Jalapeno Keno',
        cost: 5,
        topPrize: 50000,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1259',
        name: 'Gems & Blocks - WV Pop!',
        cost: 5,
        topPrize: 25000,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1265',
        name: r'Wild Side - Power $500',
        cost: 5,
        topPrize: 500,
      ),
      StateScratchGame(
        stateName: 'West Virginia',
        id: '1234',
        name: r'Gimme $50K',
        cost: 20,
        topPrize: 50000,
      ),
    ],
  };

  static const Map<String, String> _sourceUrls = {
    'California': 'https://www.calottery.com/en/scratchers',
    'Georgia':
        'https://www.galottery.com/en-us/games/scratchers/scratchers-top-prizes-claimed.html',
    'Florida': 'https://floridalottery.com/games/scratch-offs',
    'Tennessee': 'https://tnlottery.com/new-instant-games/',
    'Virginia': 'https://www.valottery.com/scratcher-search?view=0',
    'Kentucky':
        'https://www.kylottery.com/apps/scratch_offs/available_games.html',
    'Maryland': 'https://www.mdlottery.com/games/scratch-offs/',
    'Delaware': 'https://www.delottery.com/Instant-Games/Top-Prizes-Remaining',
    'New Jersey': 'https://www.njlottery.com/en-us/scratch-offs.html',
    'New York': 'https://nylottery.ny.gov/scratch-off-game/',
    'Ohio': 'https://www.ohiolottery.com/games/scratch-offs',
    'West Virginia': 'https://wvlottery.com/games/scratch-offs/',
  };

  /// Published catalogs replace the bundled snapshot for their own state.
  /// This lets the app receive a complete official catalog refresh without
  /// treating old, bundled ticket availability as still current.
  static final Map<String, List<StateScratchGame>> _publishedCatalogs =
      <String, List<StateScratchGame>>{};
  static final Map<String, String> _publishedSourceUrls = <String, String>{};
  static final ValueNotifier<int> changes = ValueNotifier<int>(0);

  static List<StateScratchGame> gamesFor(String stateName) =>
      _publishedCatalogs[stateName] ?? _catalogs[stateName] ?? const [];

  static bool hasCatalog(String stateName) => gamesFor(stateName).isNotEmpty;

  static String? sourceUrlFor(String stateName) =>
      _publishedSourceUrls[stateName] ?? _sourceUrls[stateName];

  static void usePublishedCatalogs(
    Map<String, List<StateScratchGame>> catalogs, {
    Map<String, String> sourceUrls = const <String, String>{},
  }) {
    _publishedCatalogs
      ..clear()
      ..addAll(
        catalogs.map(
          (stateName, games) =>
              MapEntry(stateName, List<StateScratchGame>.unmodifiable(games)),
        ),
      );
    _publishedSourceUrls
      ..clear()
      ..addAll(sourceUrls);
    changes.value++;
  }
}
