class StateModel {
  final String name;
  final String abbreviation;

  const StateModel({required this.name, required this.abbreviation});
}

const List<StateModel> allStates = [
  StateModel(name: "Alabama", abbreviation: "AL"),
  StateModel(name: "Alaska", abbreviation: "AK"),
  StateModel(name: "Arizona", abbreviation: "AZ"),
  StateModel(name: "Arkansas", abbreviation: "AR"),
  StateModel(name: "California", abbreviation: "CA"),
  StateModel(name: "Colorado", abbreviation: "CO"),
  StateModel(name: "Connecticut", abbreviation: "CT"),
  StateModel(name: "Delaware", abbreviation: "DE"),
  StateModel(name: "Florida", abbreviation: "FL"),
  StateModel(name: "Georgia", abbreviation: "GA"),
  StateModel(name: "Hawaii", abbreviation: "HI"),
  StateModel(name: "Idaho", abbreviation: "ID"),
  StateModel(name: "Illinois", abbreviation: "IL"),
  StateModel(name: "Indiana", abbreviation: "IN"),
  StateModel(name: "Iowa", abbreviation: "IA"),
  StateModel(name: "Kansas", abbreviation: "KS"),
  StateModel(name: "Kentucky", abbreviation: "KY"),
  StateModel(name: "Louisiana", abbreviation: "LA"),
  StateModel(name: "Maine", abbreviation: "ME"),
  StateModel(name: "Maryland", abbreviation: "MD"),
  StateModel(name: "Massachusetts", abbreviation: "MA"),
  StateModel(name: "Michigan", abbreviation: "MI"),
  StateModel(name: "Minnesota", abbreviation: "MN"),
  StateModel(name: "Mississippi", abbreviation: "MS"),
  StateModel(name: "Missouri", abbreviation: "MO"),
  StateModel(name: "Montana", abbreviation: "MT"),
  StateModel(name: "Nebraska", abbreviation: "NE"),
  StateModel(name: "Nevada", abbreviation: "NV"),
  StateModel(name: "New Hampshire", abbreviation: "NH"),
  StateModel(name: "New Jersey", abbreviation: "NJ"),
  StateModel(name: "New Mexico", abbreviation: "NM"),
  StateModel(name: "New York", abbreviation: "NY"),
  StateModel(name: "North Carolina", abbreviation: "NC"),
  StateModel(name: "North Dakota", abbreviation: "ND"),
  StateModel(name: "Ohio", abbreviation: "OH"),
  StateModel(name: "Oklahoma", abbreviation: "OK"),
  StateModel(name: "Oregon", abbreviation: "OR"),
  StateModel(name: "Pennsylvania", abbreviation: "PA"),
  StateModel(name: "Rhode Island", abbreviation: "RI"),
  StateModel(name: "South Carolina", abbreviation: "SC"),
  StateModel(name: "South Dakota", abbreviation: "SD"),
  StateModel(name: "Tennessee", abbreviation: "TN"),
  StateModel(name: "Texas", abbreviation: "TX"),
  StateModel(name: "Utah", abbreviation: "UT"),
  StateModel(name: "Vermont", abbreviation: "VT"),
  StateModel(name: "Virginia", abbreviation: "VA"),
  StateModel(name: "Washington", abbreviation: "WA"),
  StateModel(name: "West Virginia", abbreviation: "WV"),
  StateModel(name: "Wisconsin", abbreviation: "WI"),
  StateModel(name: "Wyoming", abbreviation: "WY"),
];
